name: Checks

on:
  push:
    branches:
      - 'main'
  pull_request:


jobs:
  run_checks:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: '${{ github.workspace }}/packages'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: pip3 install -r requirements.txt
      shell: bash

    - name: Run tests
      run: python3 -m unittest
      shell: bash

    - name: Type checking
      uses: jakebailey/pyright-action@v1

